[General]
# Le cambiamos el nombre aquí también por si acaso
Name = WirelessAADongle

# IMPORTANTE: Desactivar perfiles de audio
# Esto evita que el teléfono vea al dongle como "Auriculares" o "Manos libres"
Disable = Headset,Handsfree,AudioSink,AudioSource,A2DP,AVRCP,HFP,HSP

# Clase de dispositivo: "Uncategorized" (para que no parezca audio)
Class = 0x000000

# Otros ajustes recomendados
DiscoverableTimeout = 0
PairableTimeout = 0
AutoEnable = true
