// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WifiInfoResponse.proto

#include "WifiInfoResponse.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR WifiInfoResponse::WifiInfoResponse(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.ssid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bssid_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.security_mode_)*/0
  , /*decltype(_impl_.access_point_type_)*/0} {}
struct WifiInfoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WifiInfoResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~WifiInfoResponseDefaultTypeInternal() {}
  union {
    WifiInfoResponse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WifiInfoResponseDefaultTypeInternal _WifiInfoResponse_default_instance_;
bool AccessPointType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> AccessPointType_strings[2] = {};

static const char AccessPointType_names[] =
  "DYNAMIC"
  "STATIC";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry AccessPointType_entries[] = {
  { {AccessPointType_names + 0, 7}, 1 },
  { {AccessPointType_names + 7, 6}, 0 },
};

static const int AccessPointType_entries_by_number[] = {
  1, // 0 -> STATIC
  0, // 1 -> DYNAMIC
};

const std::string& AccessPointType_Name(
    AccessPointType value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          AccessPointType_entries,
          AccessPointType_entries_by_number,
          2, AccessPointType_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      AccessPointType_entries,
      AccessPointType_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     AccessPointType_strings[idx].get();
}
bool AccessPointType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccessPointType* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      AccessPointType_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<AccessPointType>(int_value);
  }
  return success;
}
bool SecurityMode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 8:
    case 12:
    case 20:
    case 24:
    case 28:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> SecurityMode_strings[10] = {};

static const char SecurityMode_names[] =
  "OPEN"
  "UNKNOWN_SECURITY_MODE"
  "WEP_128"
  "WEP_64"
  "WPA2_ENTERPRISE"
  "WPA2_PERSONAL"
  "WPA_ENTERPRISE"
  "WPA_PERSONAL"
  "WPA_WPA2_ENTERPRISE"
  "WPA_WPA2_PERSONAL";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry SecurityMode_entries[] = {
  { {SecurityMode_names + 0, 4}, 1 },
  { {SecurityMode_names + 4, 21}, 0 },
  { {SecurityMode_names + 25, 7}, 3 },
  { {SecurityMode_names + 32, 6}, 2 },
  { {SecurityMode_names + 38, 15}, 24 },
  { {SecurityMode_names + 53, 13}, 8 },
  { {SecurityMode_names + 66, 14}, 20 },
  { {SecurityMode_names + 80, 12}, 4 },
  { {SecurityMode_names + 92, 19}, 28 },
  { {SecurityMode_names + 111, 17}, 12 },
};

static const int SecurityMode_entries_by_number[] = {
  1, // 0 -> UNKNOWN_SECURITY_MODE
  0, // 1 -> OPEN
  3, // 2 -> WEP_64
  2, // 3 -> WEP_128
  7, // 4 -> WPA_PERSONAL
  5, // 8 -> WPA2_PERSONAL
  9, // 12 -> WPA_WPA2_PERSONAL
  6, // 20 -> WPA_ENTERPRISE
  4, // 24 -> WPA2_ENTERPRISE
  8, // 28 -> WPA_WPA2_ENTERPRISE
};

const std::string& SecurityMode_Name(
    SecurityMode value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          SecurityMode_entries,
          SecurityMode_entries_by_number,
          10, SecurityMode_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      SecurityMode_entries,
      SecurityMode_entries_by_number,
      10, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     SecurityMode_strings[idx].get();
}
bool SecurityMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SecurityMode* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      SecurityMode_entries, 10, name, &int_value);
  if (success) {
    *value = static_cast<SecurityMode>(int_value);
  }
  return success;
}

// ===================================================================

class WifiInfoResponse::_Internal {
 public:
  using HasBits = decltype(std::declval<WifiInfoResponse>()._impl_._has_bits_);
  static void set_has_ssid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_bssid(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_security_mode(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_access_point_type(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000001f) ^ 0x0000001f) != 0;
  }
};

WifiInfoResponse::WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:WifiInfoResponse)
}
WifiInfoResponse::WifiInfoResponse(const WifiInfoResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  WifiInfoResponse* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ssid_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.bssid_){}
    , decltype(_impl_.security_mode_){}
    , decltype(_impl_.access_point_type_){}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.ssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_ssid()) {
    _this->_impl_.ssid_.Set(from._internal_ssid(), 
      _this->GetArenaForAllocation());
  }
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_key()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.bssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_bssid()) {
    _this->_impl_.bssid_.Set(from._internal_bssid(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.security_mode_, &from._impl_.security_mode_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.access_point_type_) -
    reinterpret_cast<char*>(&_impl_.security_mode_)) + sizeof(_impl_.access_point_type_));
  // @@protoc_insertion_point(copy_constructor:WifiInfoResponse)
}

inline void WifiInfoResponse::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.ssid_){}
    , decltype(_impl_.key_){}
    , decltype(_impl_.bssid_){}
    , decltype(_impl_.security_mode_){0}
    , decltype(_impl_.access_point_type_){0}
  };
  _impl_.ssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.ssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.bssid_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bssid_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

WifiInfoResponse::~WifiInfoResponse() {
  // @@protoc_insertion_point(destructor:WifiInfoResponse)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void WifiInfoResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.ssid_.Destroy();
  _impl_.key_.Destroy();
  _impl_.bssid_.Destroy();
}

void WifiInfoResponse::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void WifiInfoResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:WifiInfoResponse)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.ssid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.bssid_.ClearNonDefaultToEmpty();
    }
  }
  if (cached_has_bits & 0x00000018u) {
    ::memset(&_impl_.security_mode_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.access_point_type_) -
        reinterpret_cast<char*>(&_impl_.security_mode_)) + sizeof(_impl_.access_point_type_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<std::string>();
}

const char* WifiInfoResponse::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required string ssid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_ssid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required string key = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required string bssid = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_bssid();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required .SecurityMode security_mode = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::SecurityMode_IsValid(val))) {
            _internal_set_security_mode(static_cast<::SecurityMode>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(4, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // required .AccessPointType access_point_type = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::AccessPointType_IsValid(val))) {
            _internal_set_access_point_type(static_cast<::AccessPointType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(5, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* WifiInfoResponse::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:WifiInfoResponse)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // required string ssid = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_ssid(), target);
  }

  // required string key = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_key(), target);
  }

  // required string bssid = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_bssid(), target);
  }

  // required .SecurityMode security_mode = 4;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      4, this->_internal_security_mode(), target);
  }

  // required .AccessPointType access_point_type = 5;
  if (cached_has_bits & 0x00000010u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      5, this->_internal_access_point_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WifiInfoResponse)
  return target;
}

size_t WifiInfoResponse::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:WifiInfoResponse)
  size_t total_size = 0;

  if (_internal_has_ssid()) {
    // required string ssid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());
  }

  if (_internal_has_key()) {
    // required string key = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  if (_internal_has_bssid()) {
    // required string bssid = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bssid());
  }

  if (_internal_has_security_mode()) {
    // required .SecurityMode security_mode = 4;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_security_mode());
  }

  if (_internal_has_access_point_type()) {
    // required .AccessPointType access_point_type = 5;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_access_point_type());
  }

  return total_size;
}
size_t WifiInfoResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WifiInfoResponse)
  size_t total_size = 0;

  if (((_impl_._has_bits_[0] & 0x0000001f) ^ 0x0000001f) == 0) {  // All required fields are present.
    // required string ssid = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_ssid());

    // required string key = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());

    // required string bssid = 3;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_bssid());

    // required .SecurityMode security_mode = 4;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_security_mode());

    // required .AccessPointType access_point_type = 5;
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_access_point_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WifiInfoResponse::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const WifiInfoResponse*>(
      &from));
}

void WifiInfoResponse::MergeFrom(const WifiInfoResponse& from) {
  WifiInfoResponse* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:WifiInfoResponse)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000001fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_ssid(from._internal_ssid());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_key(from._internal_key());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_bssid(from._internal_bssid());
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.security_mode_ = from._impl_.security_mode_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.access_point_type_ = from._impl_.access_point_type_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void WifiInfoResponse::CopyFrom(const WifiInfoResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WifiInfoResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WifiInfoResponse::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_impl_._has_bits_)) return false;
  return true;
}

void WifiInfoResponse::InternalSwap(WifiInfoResponse* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.ssid_, lhs_arena,
      &other->_impl_.ssid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bssid_, lhs_arena,
      &other->_impl_.bssid_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(WifiInfoResponse, _impl_.access_point_type_)
      + sizeof(WifiInfoResponse::_impl_.access_point_type_)
      - PROTOBUF_FIELD_OFFSET(WifiInfoResponse, _impl_.security_mode_)>(
          reinterpret_cast<char*>(&_impl_.security_mode_),
          reinterpret_cast<char*>(&other->_impl_.security_mode_));
}

std::string WifiInfoResponse::GetTypeName() const {
  return "WifiInfoResponse";
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::WifiInfoResponse*
Arena::CreateMaybeMessage< ::WifiInfoResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::WifiInfoResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
