// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WifiInfoResponse.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_WifiInfoResponse_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_WifiInfoResponse_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_WifiInfoResponse_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_WifiInfoResponse_2eproto {
  static const uint32_t offsets[];
};
class WifiInfoResponse;
struct WifiInfoResponseDefaultTypeInternal;
extern WifiInfoResponseDefaultTypeInternal _WifiInfoResponse_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::WifiInfoResponse* Arena::CreateMaybeMessage<::WifiInfoResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

enum AccessPointType : int {
  STATIC = 0,
  DYNAMIC = 1
};
bool AccessPointType_IsValid(int value);
constexpr AccessPointType AccessPointType_MIN = STATIC;
constexpr AccessPointType AccessPointType_MAX = DYNAMIC;
constexpr int AccessPointType_ARRAYSIZE = AccessPointType_MAX + 1;

const std::string& AccessPointType_Name(AccessPointType value);
template<typename T>
inline const std::string& AccessPointType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, AccessPointType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function AccessPointType_Name.");
  return AccessPointType_Name(static_cast<AccessPointType>(enum_t_value));
}
bool AccessPointType_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, AccessPointType* value);
enum SecurityMode : int {
  UNKNOWN_SECURITY_MODE = 0,
  OPEN = 1,
  WEP_64 = 2,
  WEP_128 = 3,
  WPA_PERSONAL = 4,
  WPA2_PERSONAL = 8,
  WPA_WPA2_PERSONAL = 12,
  WPA_ENTERPRISE = 20,
  WPA2_ENTERPRISE = 24,
  WPA_WPA2_ENTERPRISE = 28
};
bool SecurityMode_IsValid(int value);
constexpr SecurityMode SecurityMode_MIN = UNKNOWN_SECURITY_MODE;
constexpr SecurityMode SecurityMode_MAX = WPA_WPA2_ENTERPRISE;
constexpr int SecurityMode_ARRAYSIZE = SecurityMode_MAX + 1;

const std::string& SecurityMode_Name(SecurityMode value);
template<typename T>
inline const std::string& SecurityMode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SecurityMode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SecurityMode_Name.");
  return SecurityMode_Name(static_cast<SecurityMode>(enum_t_value));
}
bool SecurityMode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SecurityMode* value);
// ===================================================================

class WifiInfoResponse final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:WifiInfoResponse) */ {
 public:
  inline WifiInfoResponse() : WifiInfoResponse(nullptr) {}
  ~WifiInfoResponse() override;
  explicit PROTOBUF_CONSTEXPR WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  WifiInfoResponse(const WifiInfoResponse& from);
  WifiInfoResponse(WifiInfoResponse&& from) noexcept
    : WifiInfoResponse() {
    *this = ::std::move(from);
  }

  inline WifiInfoResponse& operator=(const WifiInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WifiInfoResponse& operator=(WifiInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const std::string& unknown_fields() const {
    return _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString);
  }
  inline std::string* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<std::string>();
  }

  static const WifiInfoResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const WifiInfoResponse* internal_default_instance() {
    return reinterpret_cast<const WifiInfoResponse*>(
               &_WifiInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(WifiInfoResponse& a, WifiInfoResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(WifiInfoResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WifiInfoResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WifiInfoResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<WifiInfoResponse>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const WifiInfoResponse& from);
  void MergeFrom(const WifiInfoResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(WifiInfoResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "WifiInfoResponse";
  }
  protected:
  explicit WifiInfoResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSsidFieldNumber = 1,
    kKeyFieldNumber = 2,
    kBssidFieldNumber = 3,
    kSecurityModeFieldNumber = 4,
    kAccessPointTypeFieldNumber = 5,
  };
  // required string ssid = 1;
  bool has_ssid() const;
  private:
  bool _internal_has_ssid() const;
  public:
  void clear_ssid();
  const std::string& ssid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_ssid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_ssid();
  PROTOBUF_NODISCARD std::string* release_ssid();
  void set_allocated_ssid(std::string* ssid);
  private:
  const std::string& _internal_ssid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ssid(const std::string& value);
  std::string* _internal_mutable_ssid();
  public:

  // required string key = 2;
  bool has_key() const;
  private:
  bool _internal_has_key() const;
  public:
  void clear_key();
  const std::string& key() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_key(ArgT0&& arg0, ArgT... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* key);
  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(const std::string& value);
  std::string* _internal_mutable_key();
  public:

  // required string bssid = 3;
  bool has_bssid() const;
  private:
  bool _internal_has_bssid() const;
  public:
  void clear_bssid();
  const std::string& bssid() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bssid(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bssid();
  PROTOBUF_NODISCARD std::string* release_bssid();
  void set_allocated_bssid(std::string* bssid);
  private:
  const std::string& _internal_bssid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bssid(const std::string& value);
  std::string* _internal_mutable_bssid();
  public:

  // required .SecurityMode security_mode = 4;
  bool has_security_mode() const;
  private:
  bool _internal_has_security_mode() const;
  public:
  void clear_security_mode();
  ::SecurityMode security_mode() const;
  void set_security_mode(::SecurityMode value);
  private:
  ::SecurityMode _internal_security_mode() const;
  void _internal_set_security_mode(::SecurityMode value);
  public:

  // required .AccessPointType access_point_type = 5;
  bool has_access_point_type() const;
  private:
  bool _internal_has_access_point_type() const;
  public:
  void clear_access_point_type();
  ::AccessPointType access_point_type() const;
  void set_access_point_type(::AccessPointType value);
  private:
  ::AccessPointType _internal_access_point_type() const;
  void _internal_set_access_point_type(::AccessPointType value);
  public:

  // @@protoc_insertion_point(class_scope:WifiInfoResponse)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr ssid_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bssid_;
    int security_mode_;
    int access_point_type_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_WifiInfoResponse_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// WifiInfoResponse

// required string ssid = 1;
inline bool WifiInfoResponse::_internal_has_ssid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_ssid() const {
  return _internal_has_ssid();
}
inline void WifiInfoResponse::clear_ssid() {
  _impl_.ssid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& WifiInfoResponse::ssid() const {
  // @@protoc_insertion_point(field_get:WifiInfoResponse.ssid)
  return _internal_ssid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiInfoResponse::set_ssid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000001u;
 _impl_.ssid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:WifiInfoResponse.ssid)
}
inline std::string* WifiInfoResponse::mutable_ssid() {
  std::string* _s = _internal_mutable_ssid();
  // @@protoc_insertion_point(field_mutable:WifiInfoResponse.ssid)
  return _s;
}
inline const std::string& WifiInfoResponse::_internal_ssid() const {
  return _impl_.ssid_.Get();
}
inline void WifiInfoResponse::_internal_set_ssid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ssid_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::_internal_mutable_ssid() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ssid_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::release_ssid() {
  // @@protoc_insertion_point(field_release:WifiInfoResponse.ssid)
  if (!_internal_has_ssid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* p = _impl_.ssid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiInfoResponse::set_allocated_ssid(std::string* ssid) {
  if (ssid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ssid_.SetAllocated(ssid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.ssid_.IsDefault()) {
    _impl_.ssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:WifiInfoResponse.ssid)
}

// required string key = 2;
inline bool WifiInfoResponse::_internal_has_key() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_key() const {
  return _internal_has_key();
}
inline void WifiInfoResponse::clear_key() {
  _impl_.key_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& WifiInfoResponse::key() const {
  // @@protoc_insertion_point(field_get:WifiInfoResponse.key)
  return _internal_key();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiInfoResponse::set_key(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000002u;
 _impl_.key_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:WifiInfoResponse.key)
}
inline std::string* WifiInfoResponse::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:WifiInfoResponse.key)
  return _s;
}
inline const std::string& WifiInfoResponse::_internal_key() const {
  return _impl_.key_.Get();
}
inline void WifiInfoResponse::_internal_set_key(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::_internal_mutable_key() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.key_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::release_key() {
  // @@protoc_insertion_point(field_release:WifiInfoResponse.key)
  if (!_internal_has_key()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* p = _impl_.key_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiInfoResponse::set_allocated_key(std::string* key) {
  if (key != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.key_.SetAllocated(key, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.key_.IsDefault()) {
    _impl_.key_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:WifiInfoResponse.key)
}

// required string bssid = 3;
inline bool WifiInfoResponse::_internal_has_bssid() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_bssid() const {
  return _internal_has_bssid();
}
inline void WifiInfoResponse::clear_bssid() {
  _impl_.bssid_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& WifiInfoResponse::bssid() const {
  // @@protoc_insertion_point(field_get:WifiInfoResponse.bssid)
  return _internal_bssid();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void WifiInfoResponse::set_bssid(ArgT0&& arg0, ArgT... args) {
 _impl_._has_bits_[0] |= 0x00000004u;
 _impl_.bssid_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:WifiInfoResponse.bssid)
}
inline std::string* WifiInfoResponse::mutable_bssid() {
  std::string* _s = _internal_mutable_bssid();
  // @@protoc_insertion_point(field_mutable:WifiInfoResponse.bssid)
  return _s;
}
inline const std::string& WifiInfoResponse::_internal_bssid() const {
  return _impl_.bssid_.Get();
}
inline void WifiInfoResponse::_internal_set_bssid(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.bssid_.Set(value, GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::_internal_mutable_bssid() {
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.bssid_.Mutable(GetArenaForAllocation());
}
inline std::string* WifiInfoResponse::release_bssid() {
  // @@protoc_insertion_point(field_release:WifiInfoResponse.bssid)
  if (!_internal_has_bssid()) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  auto* p = _impl_.bssid_.Release();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bssid_.IsDefault()) {
    _impl_.bssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void WifiInfoResponse::set_allocated_bssid(std::string* bssid) {
  if (bssid != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.bssid_.SetAllocated(bssid, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bssid_.IsDefault()) {
    _impl_.bssid_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:WifiInfoResponse.bssid)
}

// required .SecurityMode security_mode = 4;
inline bool WifiInfoResponse::_internal_has_security_mode() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_security_mode() const {
  return _internal_has_security_mode();
}
inline void WifiInfoResponse::clear_security_mode() {
  _impl_.security_mode_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline ::SecurityMode WifiInfoResponse::_internal_security_mode() const {
  return static_cast< ::SecurityMode >(_impl_.security_mode_);
}
inline ::SecurityMode WifiInfoResponse::security_mode() const {
  // @@protoc_insertion_point(field_get:WifiInfoResponse.security_mode)
  return _internal_security_mode();
}
inline void WifiInfoResponse::_internal_set_security_mode(::SecurityMode value) {
  assert(::SecurityMode_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.security_mode_ = value;
}
inline void WifiInfoResponse::set_security_mode(::SecurityMode value) {
  _internal_set_security_mode(value);
  // @@protoc_insertion_point(field_set:WifiInfoResponse.security_mode)
}

// required .AccessPointType access_point_type = 5;
inline bool WifiInfoResponse::_internal_has_access_point_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool WifiInfoResponse::has_access_point_type() const {
  return _internal_has_access_point_type();
}
inline void WifiInfoResponse::clear_access_point_type() {
  _impl_.access_point_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline ::AccessPointType WifiInfoResponse::_internal_access_point_type() const {
  return static_cast< ::AccessPointType >(_impl_.access_point_type_);
}
inline ::AccessPointType WifiInfoResponse::access_point_type() const {
  // @@protoc_insertion_point(field_get:WifiInfoResponse.access_point_type)
  return _internal_access_point_type();
}
inline void WifiInfoResponse::_internal_set_access_point_type(::AccessPointType value) {
  assert(::AccessPointType_IsValid(value));
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.access_point_type_ = value;
}
inline void WifiInfoResponse::set_access_point_type(::AccessPointType value) {
  _internal_set_access_point_type(value);
  // @@protoc_insertion_point(field_set:WifiInfoResponse.access_point_type)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::AccessPointType> : ::std::true_type {};
template <> struct is_proto_enum< ::SecurityMode> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_WifiInfoResponse_2eproto
